# Generated by Django 4.2.1 on 2023-05-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
