# Generated by Django 4.2.1 on 2023-05-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
